[build-system]
requires = ["setuptools>=60"]
build-backend = "setuptools.build_meta"

[project]
name = "cardapi"
version = "0.1.0"
dependencies = []  # runtime deps already listed in requirements.txt
